[env:cardputer-adv]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB

lib_deps =
    m5stack/M5Cardputer @ ^1.0.0
    h2zero/NimBLE-Arduino @ ^1.4.2
    mikalhart/TinyGPSPlus @ ^1.0.3
    jgromes/RadioLib @ ^6.6.0
    bblanchon/ArduinoJson @ ^7.2.0

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DCONFIG_NIMBLE_ENABLED=1
