#!/usr/bin/env python3
"""Generate src/oui_db.h from data/oui.json.

Run from project root:  python3 tools/gen_oui_header.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent


def pack_oui(prefix: str) -> int:
    b = prefix.upper().replace("-", ":").split(":")
    return (int(b[0], 16) << 16) | (int(b[1], 16) << 8) | int(b[2], 16)


def main() -> None:
    with open(ROOT / "data" / "oui.json") as f:
        data = json.load(f)

    normal: list[tuple[int, str]] = []
    la: list[int] = []

    for oui in data["vendors"]["ring"]["oui"]:
        normal.append((pack_oui(oui["prefix"]), "VENDOR_RING"))

    for oui in data["vendors"]["flock"]["oui"]:
        packed = pack_oui(oui["prefix"])
        if oui.get("locally_administered"):
            la.append(packed)
        else:
            normal.append((packed, "VENDOR_FLOCK"))

    normal.sort(key=lambda x: x[0])

    out = ROOT / "src" / "oui_db.h"
    out.parent.mkdir(exist_ok=True)

    with open(out, "w") as f:
        f.write("// AUTO-GENERATED by tools/gen_oui_header.py — do not edit\n")
        f.write("// Source: data/oui.json\n\n")
        f.write("#pragma once\n")
        f.write("#include <stddef.h>\n")
        f.write("#include <stdint.h>\n\n")

        f.write("typedef enum : uint8_t {\n")
        f.write("    VENDOR_UNKNOWN = 0,\n")
        f.write("    VENDOR_RING    = 1,\n")
        f.write("    VENDOR_FLOCK   = 2,\n")
        f.write("} VendorId;\n\n")

        f.write("typedef struct {\n")
        f.write("    uint32_t oui;    // packed (b0<<16)|(b1<<8)|b2\n")
        f.write("    VendorId vendor;\n")
        f.write("} OuiEntry;\n\n")

        f.write(f"static const OuiEntry OUI_TABLE[{len(normal)}] = {{\n")
        for key, vendor in normal:
            f.write(f"    {{0x{key:06X}u, {vendor}}},\n")
        f.write("};\n\n")
        f.write(f"static const size_t OUI_TABLE_SIZE = {len(normal)}u;\n\n")

        f.write("// Locally-administered MACs confirmed on Flock hardware\n")
        f.write(f"static const uint32_t OUI_LA_FLOCK[{len(la)}] = {{\n")
        for key in la:
            f.write(f"    0x{key:06X}u,\n")
        f.write("};\n\n")
        f.write(f"static const size_t OUI_LA_FLOCK_SIZE = {len(la)}u;\n")

    print(f"Wrote {out}  ({len(normal)} entries, {len(la)} LA entries)")


if __name__ == "__main__":
    main()
