// AUTO-GENERATED by tools/gen_oui_header.py — do not edit
// Source: data/oui.json

#pragma once
#include <stddef.h>
#include <stdint.h>

typedef enum : uint8_t {
    VENDOR_UNKNOWN = 0,
    VENDOR_RING    = 1,
    VENDOR_FLOCK   = 2,
} VendorId;

typedef struct {
    uint32_t oui;    // packed (b0<<16)|(b1<<8)|b2
    VendorId vendor;
} OuiEntry;

static const OuiEntry OUI_TABLE[44] = {
    {0x00B463u, VENDOR_RING},
    {0x00F48Du, VENDOR_FLOCK},
    {0x083A88u, VENDOR_FLOCK},
    {0x145AFCu, VENDOR_FLOCK},
    {0x187F88u, VENDOR_RING},
    {0x242BD6u, VENDOR_RING},
    {0x24B2B9u, VENDOR_FLOCK},
    {0x343EA4u, VENDOR_RING},
    {0x3C71BFu, VENDOR_FLOCK},
    {0x3C9180u, VENDOR_FLOCK},
    {0x4827EAu, VENDOR_FLOCK},
    {0x50E467u, VENDOR_RING},
    {0x54E019u, VENDOR_RING},
    {0x5800E3u, VENDOR_FLOCK},
    {0x588E81u, VENDOR_FLOCK},
    {0x5C475Eu, VENDOR_RING},
    {0x5C93A2u, VENDOR_FLOCK},
    {0x646E69u, VENDOR_FLOCK},
    {0x649A63u, VENDOR_RING},
    {0x700894u, VENDOR_FLOCK},
    {0x70C94Eu, VENDOR_FLOCK},
    {0x744CA1u, VENDOR_FLOCK},
    {0x803049u, VENDOR_FLOCK},
    {0x9035EAu, VENDOR_FLOCK},
    {0x90486Cu, VENDOR_RING},
    {0x940853u, VENDOR_FLOCK},
    {0x9C2F9Du, VENDOR_FLOCK},
    {0x9C7613u, VENDOR_RING},
    {0xA4CF12u, VENDOR_FLOCK},
    {0xAC9FC3u, VENDOR_RING},
    {0xB41E52u, VENDOR_FLOCK},
    {0xB81EA4u, VENDOR_FLOCK},
    {0xB83532u, VENDOR_FLOCK},
    {0xC03532u, VENDOR_FLOCK},
    {0xC4DBADu, VENDOR_RING},
    {0xCC3BFBu, VENDOR_RING},
    {0xD03957u, VENDOR_FLOCK},
    {0xD8F3BCu, VENDOR_FLOCK},
    {0xE04F43u, VENDOR_FLOCK},
    {0xE4AAEAu, VENDOR_FLOCK},
    {0xE8D0FCu, VENDOR_FLOCK},
    {0xEC1BBDu, VENDOR_FLOCK},
    {0xF46ADDu, VENDOR_FLOCK},
    {0xF8A2D6u, VENDOR_FLOCK},
};

static const size_t OUI_TABLE_SIZE = 44u;

// Locally-administered MACs confirmed on Flock hardware
static const uint32_t OUI_LA_FLOCK[1] = {
    0x826BF2u,
};

static const size_t OUI_LA_FLOCK_SIZE = 1u;
